{{ $release := .Release }}
{{- range $schema := .Values.postgresSchemas }}
{{- if $schema.create }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ $schema.secretName }}-secret"
  namespace: {{ $release.Namespace }}
stringData:
  username: "{{ $schema.username }}"
  password: "{{ $schema.password }}"
{{- end }}
{{- end }}