apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
stringData:
  superUserPassword: {{ .Values.superUserPassword }}
  replicationUserPassword: {{ .Values.replicationUserPassword }}
