apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: keycloak-postgres
  namespace: {{ .Release.Namespace }}
stringData:
  {{ with .Values.postgres}}
  postgresJdbcUri: "{{ .jdbcUri }}"
  postgresDbName: "{{ .dbName }}"
  postgresDbUser: "{{ .username }}"
  postgresDbPass: "{{ .password }}"
  {{ end }}
