apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: {{ .Release.Namespace }}
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      nodePort: 30080
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak
  type: LoadBalancer
